# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elenco', '0002_auto_20170224_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='user',
        ),
    ]
